[env]
SODIUM_STATIC="1"
SODIUM_REL_DIR="/libsodium"
SODIUM_DIR="${CARGO_MAKE_WORKING_DIRECTORY}${SODIUM_REL_DIR}"
SODIUM_REL_INSTALL_DIR="/install_dir"
SODIUM_INSTALL_DIR="${SODIUM_DIR}${SODIUM_REL_INSTALL_DIR}"
SODIUM_LIB_DIR="${SODIUM_INSTALL_DIR}/lib"

#### DEFAULT TASK ####

[tasks.build]
clear = true
dependencies = [
		"compile_sodium",
		"compile_rust",
		"compile_napi_binding"
]

[tasks.clean]
dependencies = [
	"clean_cmake"
]

#### RUST ####

[tasks.compile_rust]
script = [
	"cargo build --release"
]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

#### NAPI ####

[tasks.compile_napi_binding]
script = [
		"cmake -DCMAKE_BUILD_TYPE=Release .",
		"make",
		"mv libbinding.so ../build/Release/binding.node",
]

[tasks.clean_cmake]
script = [
	"rm -rf CMakeCache.txt CMakeFiles Makefile"
]

#### SODIUM ####

[tasks.sodium_clone]
script = [
	"[ -d ${SODIUM_DIR} ] || git clone https://github.com/jedisct1/libsodium ${SODIUM_DIR}"
]

[tasks.sodium_fetch]
command = "git"
args = ["-C", "${SODIUM_DIR}","fetch"]
dependencies = ["sodium_clone"]

[tasks.sodium_checkout]
command = "git"
args = ["-C",  "${SODIUM_DIR}","checkout", "origin/stable"]
dependencies = ["sodium_fetch"]

[tasks.compile_sodium]
condition_script = [
	"test ! -e ${SODIUM_LIB_DIR}/libsodium.a"
] 
script = [
	"cd ${SODIUM_DIR}",
	"./autogen.sh",
	"./configure --prefix=${SODIUM_DIR} --disable-shared --enable-static --disable-pie",
	"make -j4",
	"make install",
]
dependencies = ["sodium_checkout"]
